### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by enzymezoo-code** [multimodalart/majesty-diffusion#13]
Running with how_many_batches>1 can lead to "Cuda out of memory" errors after the first image is completed. There is a memory leak somewhere. 

Other notebooks solve this problem by putting the batch "for" loop around the do_run() function rather than inside the do_run() function. That way, whatever mystery local variable that causes this problem gets cleaned up.

**Comment by apolinario** [comment]
Thank you for the tip! I fixed it with a for loop! https://github.com/multimodalart/majesty-diffusion/commit/dd7840e54a1287d5d5b5fe734814207e23599ed5
