### ISSUE TITLE
EOF error at the Load Necessary Functions step

### ISSUE THREAD

**Issue by boswell255** [multimodalart/majesty-diffusion#16]
Getting an EOF error at the Load Necessary Functions step, Line 461.

Stack exchange says it's probably a  pickle being overwritten but that's as far as my trouble shooting skill can take me. 

Tried it in two separate colab instances, one with the Erlich model, the second with finetuned.

Thank you :)

```
`Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /usr/local/lib/python3.7/dist-packages/lpips/weights/v0.1/vgg.pth
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
[<ipython-input-14-f555e4f938e4>](https://localhost:8080/#) in <module>()
    459 #Alstro's aesthetic model
    460 aesthetic_model_336 = torch.nn.Linear(768,1).cuda()
--> 461 aesthetic_model_336.load_state_dict(torch.load(f"{model_path}/ava_vit_l_14_336_linear.pth"))
    462 
    463 aesthetic_model_224 = torch.nn.Linear(768,1).cuda()

1 frames
[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    775             "functionality.")
    776 
--> 777     magic_number = pickle_module.load(f, **pickle_load_args)
    778     if magic_number != MAGIC_NUMBER:
    779         raise RuntimeError("Invalid magic number; corrupt file?")

EOFError: Ran out of input`
```

**Comment by nicholascelestin** [comment]
Oh, it's because of the cloudflare issues with the multimodal.art site.

**Comment by boswell255** [comment]
> Oh, it's because of the cloudflare issues with the multimodal.art site.

Oh cool, hopefully just temporary then

**Comment by nicholascelestin** [comment]
Nope, it's still there even after the cloudflare issue went away on the main site.

**Comment by Dango233** [comment]
> there

Can yoy try if it is fixed now?
If not, try del models that has been downloaded, and try again.

Lmk if this is fixed

**Comment by boswell255** [comment]
Deleting and reloading everything in the models folder got it working again, thank you!
